name: Deploy To Surge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g surge
    - run: surge --project ./ --domain khans-cravings-dining.surge.sh
      env:
        SURGE_LOGIN: redwankhanbro@gmail.com
        SURGE_TOKEN: 637b3758697f562f55e7c9d8e9584f88
