name: Deploy To Surge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g surge
    - run: surge --project ./ --domain khans-cravings-dining.surge.sh --email redwankhanbro@gmail.com --password "red]#uih&tyFjh123"
